---
title: "Représentation des stats calculées par MetHis (50 000 SNP) pour des scénarios d'admixture simple multi simu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/git_repository/Stage/Simulations/SNP_YRI_GBR_adm_multi/")
# knitr::opts_knit$set(root.dir = "~/Documents/git_repository/Stage/Simulations/SNP_AFR_EUR/new_methis_bottleneck_50000_snp/alpha0.1/Nu0.01/bottle10/")

```

## Indicateur de temps
```{r}
time.ini = Sys.time()
```

Chargement des libraries et fonctions
```{r}
source("../../scriptR/functions.R")
```

### Enregistrement des fonctions
```{r}
print(difftime(Sys.time(), time.ini))
```

##Admixture récurrente

###Ne constant
```{r}
setwd("pulse_recurrent/Ne_cst/")

lst_ne_cst_adm_rec = list()
cpt = 1
vec_val_s10 = c(0.1, 0.5, 0.75)

for (val_s10 in vec_val_s10) {
  setwd(str_c("s1.0_", val_s10,"/"))
  lst_ne_cst_adm_rec[[cpt]] = data.frame.stat(seq_ne = c(100,1000,10000),
                                               max_gen = 101, max_simu = 1)
  lst_ne_cst_adm_rec[[cpt]] = delta.adm.gen.0(lst_ne_cst_adm_rec[[cpt]])
  cpt = cpt + 1
  setwd("../")
}

```

```{r}

for (i in c(1:3)) {
  write_cstt_plot(name_stat = "mean.het.adm", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/mean.he/Ne_cst/he_mean_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = 0.047,max_y = 0.065,
                  ylab="mean He")
  write_cstt_plot(name_stat = "Fst.s1.adm", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/Fst.s1.adm/Ne_cst/fst_s1_adm_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = 0,max_y = 0.1,
                  ylab=expression(paste(F[ST], " s1-adm", sep = "")))
  write_cstt_plot(name_stat = "Fst.s2.adm", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/Fst.s2.adm/Ne_cst/fst_s2_adm_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = 0,max_y = 0.1,
                  ylab=expression(paste(F[ST], " s2-adm", sep = "")))
  write_cstt_plot(name_stat = "mean.F.adm", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/mean.F/Ne_cst/F_mean_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = -0.03,max_y = 0.02,ylab="F")
  write_cstt_plot(name_stat = "f3", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/f3/Ne_cst/f3_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = -0.05,max_y = 0.05,ylab="f3")
  write_cstt_plot(name_stat = "mean.adm.props", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/mean.adm/Ne_cst/mean_adm_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = 0,max_y = 0.8,
                  ylab="Average admixture rate")
  write_cstt_plot(name_stat = "delta.adm.gen.0", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/delta.adm0.adm/Ne_cst/delta_adm0_adm_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = -0.8,max_y = 0.8,
                  ylab=expression(paste(δ[µ["observée"]-µ["théorique"]], sep = "")))
  write_cstt_plot(name_stat = "var.adm.props", mat = lst_ne_cst_adm_rec[[i]],
                  name_file =  str_c("pulse_recurrent/var.adm/Ne_cst/delta_adm0_adm_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                  min_y = 0,max_y = 0.2,
                  ylab="Variance du taux d'admixture")

}

```


###Ne croissant
```{r}
setwd("pulse_recurrent/Ne_inc/")

seq_nu = sprintf("%.2f", c(0.01, 0.25, 0.49))
seq_ne_ini = c(100)
seq_ne_fin = c(400,1000,10000)
seq_combi = as.data.frame(outer(seq_ne_ini, seq_ne_fin, FUN="paste", sep="-"))
seq_combi = as.data.frame.vector(unlist(seq_combi))[[1]]

lst_ne_inc_adm_rec = list()
cpt = 1
vec_val_s10 = c(0.1, 0.5, 0.75)

for (val_s10 in vec_val_s10) {
  setwd(str_c("s1.0_", val_s10,"/"))
  lst_ne_inc_adm_rec[[cpt]] = data.frame.increase.nu(seq_ne_ini, seq_combi, seq_nu)
  lst_ne_inc_adm_rec[[cpt]] = delta.adm.gen.0(lst_ne_inc_adm_rec[[cpt]])
  cpt = cpt + 1
  setwd("../")
}
```

```{r}

for (i in c(1:3)) {
  write_increase_plot(name_stat = "mean.het.adm", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/mean.he/Ne_inc/he_mean_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = 0.047,max_y = 0.065,
                      ylab="mean He")
  write_increase_plot(name_stat = "Fst.s1.adm", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/Fst.s1.adm/Ne_inc/fst_s1_adm_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = 0,max_y = 0.1,
                      ylab=expression(paste(F[ST], " s1-adm", sep = "")))
  write_increase_plot(name_stat = "Fst.s2.adm", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/Fst.s2.adm/Ne_inc/fst_s2_adm_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = 0,max_y = 0.1,
                      ylab=expression(paste(F[ST], " s2-adm", sep = "")))
  write_increase_plot(name_stat = "mean.F.adm", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/mean.F/Ne_inc/F_mean_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = -0.03,max_y = 0.02,ylab="F")
  write_increase_plot(name_stat = "f3", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/f3/Ne_inc/f3_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = -0.05,max_y = 0.05,ylab="f3")
  write_increase_plot(name_stat = "mean.adm.props", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/mean.adm/Ne_inc/mean_adm_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = 0,max_y = 0.8,
                      ylab="Average admixture rate")
  write_increase_plot(name_stat = "delta.adm.gen.0", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/delta.adm0.adm/Ne_inc/delta_adm0_adm_ne_inc_multi_s10_",
                                         vec_val_s10[i]),
                      min_y = -0.8,max_y = 0.8,
                      ylab=expression(paste(δ[µ["observée"]-µ["théorique"]], sep = "")))
  write_increase_plot(name_stat = "var.adm.props", mat = lst_ne_inc_adm_rec[[i]],
                      name_file =  str_c("pulse_recurrent/var.adm/Ne_inc/delta_adm0_adm_ne_cst_multi_s10_",
                                     vec_val_s10[i]),
                      min_y = 0,max_y = 0.2,
                      ylab="Variance du taux d'admixture")
}
```


###Ne bottleneck
```{r}
setwd("pulse_recurrent/Ne_bot/")

lst_ne_bot_adm_rec = list()
cpt = 1
vec_val_s10 = c(0.1, 0.5, 0.75)

for (val_s10 in vec_val_s10) {
  setwd(str_c("s1.0_", val_s10,"/"))
  lst_ne_bot_adm_rec[[cpt]] = data.frame.bottleneck(lst_ne0 = c(1000), lst_nef = c(1000),
                                                    lst_alpha = c(0.1, 0.5, 0.9),
                                                    lst_nu = c(0.01, 0.25, 0.49),
                                                    lst_bottle = c(20, 50, 80), max_simu = 1)
  lst_ne_bot_adm_rec[[cpt]] = delta.adm.gen.0(lst_ne_bot_adm_rec[[cpt]])
  cpt = cpt + 1
  setwd("../")
}

```

```{r}
for (i in c(1:3)) {
  write_bottle_plot(name_stat = "mean.het.adm", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/mean.he/Ne_bot/he_mean_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = 0.047,max_y = 0.065,
                    ylab="mean He")
  write_bottle_plot(name_stat = "Fst.s1.adm", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/Fst.s1.adm/Ne_bot/fst_s1_adm_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = 0,max_y = 0.1,
                    ylab=expression(paste(F[ST], " s1-adm", sep = "")))
  write_bottle_plot(name_stat = "Fst.s2.adm", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/Fst.s2.adm/Ne_bot/fst_s2_adm_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = 0,max_y = 0.1,
                    ylab=expression(paste(F[ST], " s2-adm", sep = "")))
  write_bottle_plot(name_stat = "mean.F.adm", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/mean.F/Ne_bot/F_mean_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = -0.03,max_y = 0.02,ylab="F")
  write_bottle_plot(name_stat = "f3", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/f3/Ne_bot/f3_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = -0.05,max_y = 0.05,ylab="f3")
  write_bottle_plot(name_stat = "mean.adm.props", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/mean.adm/Ne_bot/mean_adm_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = 0,max_y = 0.8,
                    ylab="Average admixture rate")
  write_bottle_plot(name_stat = "delta.adm.gen.0", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/delta.adm0.adm/Ne_bot/delta_adm0_adm_ne_bot_multi_s10_",
                                         vec_val_s10[i]),
                    min_y = -0.8,max_y = 0.8,
                    ylab = expression(paste(δ[µ["g"]-µ[0]], sep = "")))
  write_bottle_plot(name_stat = "var.adm.props", mat = lst_ne_bot_adm_rec[[i]],
                    name_file =  str_c("pulse_recurrent/var.adm/Ne_bot/delta_adm0_adm_ne_cst_multi_s10_",
                                       vec_val_s10[i]),
                    min_y = 0,max_y = 0.2,
                    ylab="Variance du taux d'admixture")
}
```


##Admixture ponctuelle

###Ne constante
```{r}
setwd("pulse_ponctuel/Ne_cst/")

lst_ne_cst_adm_pct = list()
cpt = 1
vec_val_s10 = c(0.1, 0.5, 0.75)

for (val_s10 in vec_val_s10) {
  setwd(str_c("s1.0_", val_s10,"/"))
  lst_ne_cst_adm_pct[[cpt]] = data.frame.stat(seq_ne = c(100,1000,10000),max_gen = 101, max_simu = 20)
  lst_ne_cst_adm_pct[[cpt]] = delta.adm.gen.0(lst_ne_cst_adm_pct[[cpt]])
  lst_ne_cst_adm_pct[[cpt]]$time_pulse_s1 = (rep(lst_ne_cst_adm_pct[[cpt]]$Generation[which(lst_ne_cst_adm_pct[[cpt]]$s1.0 != 0 & lst_ne_cst_adm_pct[[cpt]]$Generation != 0)], each = 101))
  lst_ne_cst_adm_pct[[cpt]]$time_pulse_s2 = (rep(lst_ne_cst_adm_pct[[cpt]]$Generation[which(lst_ne_cst_adm_pct[[cpt]]$s2.0 != 0 & lst_ne_cst_adm_pct[[cpt]]$Generation != 0)], each = 101))
  cpt = cpt + 1
  setwd("../")
}
```


```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "mean.het.adm",
                         min_y = 0.02, max_y = 0.064, name_dir = "mean.he",
                         ylab = "mean He",title = TRUE)

plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "mean.het.adm",
                         min_y = 0.02, max_y = 0.064, name_color = "time_pulse_s2",
                         name_dir = "mean.he",ylab="mean He",title = TRUE)
```

```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(1000,10000),
                         seq_s1 = c(0.1, 0.5,0.75), name_stat = "mean.het.adm",
                         min_y = 0.047, max_y = 0.064, name_dir = "mean.he",
                         ylab = "mean He",yas1 = 0.051,yas2 = 0.050, title=TRUE)
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(1000,10000),
                         seq_s1 = c(0.1, 0.5,0.75), name_stat = "mean.het.adm",
                         min_y = 0.047, max_y = 0.064, name_dir = "mean.he",
                         ylab = "mean He",yas1 = 0.051,yas2 = 0.050, title=TRUE,name_color = "time_pulse_s2")
```


```{r}
ne_tot = rbind(lst_ne_cst_adm_pct[[1]], lst_ne_cst_adm_pct[[2]], lst_ne_cst_adm_pct[[3]])
ne_tot$flag = rep(c(1:180), each = 101)
```

```{r}
plot_stat_gen(df = ne_tot, gen = ne_tot$Generation, stat = ne_tot$mean.het.adm,
              group_col = ne_tot$flag, color_col = ne_tot$Ne,
              titre = "He en fonction gen")
```



```{r}
plot_adm_ponctuel_ne_cst_last_pulse(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "mean.het.adm",
                         min_y = 0.02, max_y = 0.063)
```

```{r}
plot_adm_ponctuel_ne_cst_minus(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "mean.het.adm",
                         min_y = 0.02, max_y = 0.063)
```


```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "Fst.s1.adm",
                         min_y = 0, max_y = 0.4,yas1 = 0.38,yas2 = 0.35,
                         name_dir = "Fst.s1.adm",
                         ylab = expression(paste(F[ST], " s1-adm", sep = "")))
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "Fst.s1.adm",
                         min_y = 0, max_y = 0.4,yas1 = 0.38,yas2 = 0.35,
                         name_color = "time_pulse_s2",
                         name_dir = "Fst.s1.adm",
                         ylab = expression(paste(F[ST], " s1-adm", sep = "")))
```

```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "Fst.s2.adm",
                         min_y = -0.01, max_y = 0.4,yas1 = 0.38,yas2 = 0.35,
                         name_dir = "Fst.s2.adm",
                         ylab = expression(paste(F[ST], " s2-adm", sep = "")))
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "Fst.s2.adm",
                         min_y = -0.01, max_y = 0.4,yas1 = 0.38,yas2 = 0.35,
                         name_dir = "Fst.s2.adm",
                         ylab = expression(paste(F[ST], " s2-adm", sep = "")))
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "Fst.s2.adm",
                         min_y = -0.01, max_y = 0.4,yas1 = 0.38,yas2 = 0.35,
                         name_color = "time_pulse_s2",
                         name_dir = "Fst.s2.adm",
                         ylab = expression(paste(F[ST], " s2-adm", sep = "")))
```

```{r}
plot_adm_ponctuel_ne_cst_minus(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "Fst.s2.adm",
                         min_y = -0.01, max_y = 0.4)
```


```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "f3",
                         min_y = -0.05,max_y = 0.8,yas1 = 0.75,yas2 = 0.69,
                         name_dir = "f3",ylab="f3")
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "f3",
                         min_y = -0.05,max_y = 0.8,yas1 = 0.75,yas2 = 0.69,
                         name_color = "time_pulse_s2",
                         name_dir = "f3",ylab="f3")
```


```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "var.adm.props",
                         min_y = -0.01, max_y = 0.15,yas1 = 0.14,yas2 = 0.125,
                         name_dir = "var.adm",ylab="var.adm")
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "var.adm.props",
                         min_y = -0.01, max_y = 0.15,yas1 = 0.14,yas2 = 0.125,
                         name_color = "time_pulse_s2",
                         name_dir = "var.adm",ylab="var.adm")
```

```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "mean.adm.props",
                         min_y = 0.2, max_y = 0.75,yas1 = 0.235,yas2 = 0.21,
                         name_dir = "mean.adm",
                         ylab = "Average admixture rate")
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "mean.adm.props",
                         min_y = 0.2, max_y = 0.75,name_color = "time_pulse_s2",
                         yas1 = 0.235,yas2 = 0.21, name_dir = "mean.adm",
                         ylab = "Average admixture rate")
```


```{r}
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "delta.adm.gen.0",
                         min_y = -0.4, max_y = 0.4,yas1 = 0.38,yas2 = 0.35,
                         name_dir = "delta.adm0.adm",
                         ylab = expression(paste(δ[µ["g"]-µ[0]], sep = "")))
plot_adm_ponctuel_ne_cst(lst_mat = lst_ne_cst_adm_pct, seq_ne = c(100,1000,10000),
                         seq_s1 = c(0.1, 0.5, 0.75), name_stat = "delta.adm.gen.0",
                         min_y = -0.4, max_y = 0.4,name_color = "time_pulse_s2",
                         yas1 = 0.38,yas2 = 0.35, name_dir = "delta.adm0.adm",
                         ylab = expression(paste(δ[µ["g"]-µ[0]], sep = "")))
```

```{r}
mat_05_ne_cst_pct = lst_ne_cst_adm_pct[[2]]
# test = mat_05_ne_cst_pct$time_pulse_s1[which(mat_05_ne_cst_pct$Generation == 0)][1]
# mat_05_ne_cst_pct$Ne[test]
# mat_05_ne_cst_pct$delta.adm.gen.0[test]
# nrow(mat_05_ne_cst_pct)/101
# df_tmp = data.frame()
for (i in c(0:59)) {

  save_sim = i*101+101
  save_rg = mat_05_ne_cst_pct$time_pulse_s1[save_sim]
  save_ne = mat_05_ne_cst_pct$Ne[save_sim]
  save_del = mat_05_ne_cst_pct$delta.adm.gen.0[save_sim]
  if (i==0) {
    df_tmp = c(save_rg, as.numeric(as.character(save_ne)),save_del)
  }else{
    df_tmp = rbind(df_tmp, c(save_rg, as.numeric(as.character(save_ne)),save_del))
  }
  
}
df_tmp = as.data.frame(df_tmp)
colnames(df_tmp) = c("pulse", "Ne", "delta")

p = ggplot(df_tmp, aes(x = pulse, y=delta,color=as.factor(Ne))) + geom_point()
print(p)

```


##Ne croissant
```{r}
setwd("pulse_ponctuel/Ne_inc/")

lst_ne_inc_adm_pct = list()
cpt = 1
vec_val_s10 = c(0.1, 0.5, 0.75)

seq_nu = sprintf("%.2f", c(0.01, 0.25, 0.49))
seq_ne_ini = c(100)
seq_ne_fin = c(400,1000,10000)
seq_combi = as.data.frame(outer(seq_ne_ini, seq_ne_fin, FUN="paste", sep="-"))
seq_combi = as.data.frame.vector(unlist(seq_combi))[[1]]

for (val_s10 in vec_val_s10) {
  setwd(str_c("s1.0_", val_s10,"/"))
  lst_ne_inc_adm_pct[[cpt]] = data.frame.increase.nu(seq_ne_ini, seq_combi, seq_nu,max_simu = 20)
  lst_ne_inc_adm_pct[[cpt]] = delta.adm.gen.0(lst_ne_inc_adm_pct[[cpt]])
  lst_ne_inc_adm_pct[[cpt]]$time_pulse_s1 = (rep(lst_ne_inc_adm_pct[[cpt]]$Generation[which(lst_ne_inc_adm_pct[[cpt]]$s1.0 != 0 & lst_ne_inc_adm_pct[[cpt]]$Generation != 0)], each = 101))
  cpt = cpt + 1
  setwd("../")
}

```


```{r}
plot_adm_ponctuel_ne_inc(lst_mat = lst_ne_inc_adm_pct, seq_ne = seq_combi,
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         name_stat = "mean.het.adm", min_y = 0.025, max_y = 0.065,
                         name_dir = "mean.he",ylab="mean He",yas1=0.017,title=TRUE)
```


```{r}
plot_adm_ponctuel_ne_inc(lst_mat = lst_ne_inc_adm_pct, seq_ne = seq_combi,
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         name_stat = "Fst.s1.adm", min_y = -0.01, max_y = 0.3,
                         name_dir = "Fst.s1.adm",
                         ylab = expression(paste(F[ST], " s1-adm", sep = "")),
                         yas1=0.42)
```

```{r}
plot_adm_ponctuel_ne_inc(lst_mat = lst_ne_inc_adm_pct, seq_ne = seq_combi,
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         name_stat = "f3", min_y = -0.1, max_y = 1.1,name_dir = "f3",ylab="f3",
                         yas1=0.7)
```

```{r}
plot_adm_ponctuel_ne_inc(lst_mat = lst_ne_inc_adm_pct, seq_ne = seq_combi,
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         name_stat = "mean.adm.props", min_y = 0.2, max_y = 0.75,
                         name_dir = "mean.adm",ylab="Average admixture rate",
                         yas1=0.21,title=TRUE)
```


```{r}
plot_adm_ponctuel_ne_inc(lst_mat = lst_ne_inc_adm_pct, seq_ne = seq_combi,
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         name_stat = "var.adm.props", min_y = -0.01, max_y = 0.15,
                         name_dir = "var.adm",ylab = "Var adm props",yas1=0.14)
```


```{r}
plot_adm_ponctuel_ne_inc(lst_mat = lst_ne_inc_adm_pct, seq_ne = seq_combi,
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         name_stat = "delta.adm.gen.0", min_y = -0.3, max_y = 0.5,
                         name_dir = "delta.adm0.adm",
                         ylab = expression(paste(δ[µ["g"]-µ[0]], sep = "")),yas1=-0.38)
```


##Ne bottleneck
```{r}
setwd("pulse_ponctuel/Ne_bot/")

lst_ne_bot_adm_pct = list()
cpt = 1
vec_val_s10 = c(0.1, 0.5, 0.75)

for (val_s10 in vec_val_s10) {
  setwd(str_c("s1.0_", val_s10,"/"))
  lst_ne_bot_adm_pct[[cpt]] = data.frame.bottleneck(lst_ne0 = c(1000), lst_nef = c(1000),
                                                    lst_alpha = c(0.1, 0.5, 0.9),
                                                    lst_nu = c(0.01, 0.25, 0.49),
                                                    lst_bottle = c(20, 50, 80), max_simu = 20)
  lst_ne_bot_adm_pct[[cpt]] = delta.adm.gen.0(lst_ne_bot_adm_pct[[cpt]])
  lst_ne_bot_adm_pct[[cpt]]$time_pulse_s1 = (rep(lst_ne_bot_adm_pct[[cpt]]$Generation[which(lst_ne_bot_adm_pct[[cpt]]$s1.0 != 0 & lst_ne_bot_adm_pct[[cpt]]$Generation != 0)], each = 101))
  cpt = cpt + 1
  setwd("../")
}


```


```{r}
plot_adm_ponctuel_ne_bot(lst_mat = lst_ne_bot_adm_pct, seq_ne = c("1000-1000"), 
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         seq_alpha = c(0.1,0.5),seq_bot = c(20,50,80),
                         name_stat = "mean.het.adm",min_y = 0.01,max_y = 0.07,
                         name_dir = "mean.he",ylab="mean He",yas1=0.017,title=TRUE)
```

```{r}
plot_adm_ponctuel_ne_bot(lst_mat = lst_ne_bot_adm_pct, seq_ne = c("1000-1000"), 
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.25, 0.49),
                         seq_alpha = c(0.1),seq_bot = c(20,50,80),
                         name_stat = "mean.het.adm",min_y = 0.035,max_y = 0.07,
                         name_dir = "mean.he",ylab="mean He",yas1=0.017,title=TRUE)
```


```{r}
plot_adm_ponctuel_ne_bot(lst_mat = lst_ne_bot_adm_pct, seq_ne = c("1000-1000"), 
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         seq_alpha = c(0.1,0.5),seq_bot = c(20,50,80),
                         name_stat = "Fst.s1.adm",min_y = 0,max_y = 0.22,
                         name_dir = "Fst.s1.adm",
                         ylab = expression(paste(F[ST], " s1-adm", sep = "")),
                         yas1=0.37)
```


```{r}
plot_adm_ponctuel_ne_bot(lst_mat = lst_ne_bot_adm_pct, seq_ne = c("1000-1000"), 
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01,0.25,0.49),
                         seq_alpha = c(0.1),seq_bot = c(20,50,80),
                         name_stat = "mean.adm.props",min_y = 0.2,max_y = 0.75,
                         name_dir = "mean.adm",ylab="Average admixture rate",
                         yas1=0.2,title=TRUE)
```

```{r}
plot_adm_ponctuel_ne_bot(lst_mat = lst_ne_bot_adm_pct, seq_ne = c("1000-1000"), 
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         seq_alpha = c(0.1),seq_bot = c(20,50,80),
                         name_stat = "var.adm.props",min_y = -0.05,max_y = 0.15,
                         name_dir = "var.adm",ylab="var adm props",yas1=0.14)
```


```{r}
plot_adm_ponctuel_ne_bot(lst_mat = lst_ne_bot_adm_pct, seq_ne = c("1000-1000"), 
                         seq_s1 = c(0.1, 0.5, 0.75), seq_u = c(0.01, 0.25, 0.49),
                         seq_alpha = c(0.1,0.5),seq_bot = c(20,50,80),
                         name_stat = "delta.adm.gen.0",min_y = -0.3,max_y = 0.5,
                         name_dir = "delta.adm0.adm",
                         ylab = expression(paste(δ[µ["g"]-µ[0]], sep = "")),
                         yas1=0.38)
```


```{r}
print(difftime(Sys.time(), time.ini))
```
